### ISSUE TITLE
High Pitched Audio on PAL Games (PS3)

### ISSUE THREAD

**Issue by HiroTex** [sahlberg/pop-fe#10]
I had trouble converting some PAL Games with the program, the games' issues are High Pitched voices and/or SFX, both In Game and even in FMVs.
The games are Wacky Races (PAL) [SLES_024.68] and Broken Sword II: The Smoking Mirror (Spain) [SCES_008.02] for now.
I don't know the cause of the problem yet. The video output (60hz) is not the problem as the first Broken Sword (Spain) works well.
I don't know if this is an issue with the program itself, with the conversion process, with the PS1 Emulator on the PS3, or with the actual game rips.

**Comment by sahlberg** [comment]
Pop-fe shouldn't be processing any of the sound (EXCEPT CD-DA tracks which are converted via an external tool but you mention voices and sfx so this would not be a CD-DA issue).
So it is likely an emulator issue.

However, pop-fe DOES specify to the emulator which video resolutions are supported which could impact PAL/NTSC games.
It currently hardcodes RESOLUTION to 1,   see https://github.com/sahlberg/pop-fe/blob/275827993e9fed21d97355d65d8586053de84162/pop-fe.py#L576

Can you try to change this line from 1, to instead be 2/4/8/16/32 and see if any of those choices make a difference?
See here for what this field contains: https://www.psdevwiki.com/ps3/PARAM.SFO#RESOLUTION

**Comment by HiroTex** [comment]
Thank you, once again, you are indeed correct, this fixed the issue. 
It seems that PAL games have a RESOLUTION value of 2 (I've confirmed it by looking at official PAL Games' PARAM.SFO files from Crash Bandicoot 2, 3 and several other ones), while NTSC games have always a value of 1.

**Comment by sahlberg** [comment]
Awesome.
I will update pop-fe to automatically set it to 2 for PAL games   and also add a command line argument if someone needs to override it or force a specific setting.

Thanks for testing.

**Comment by sahlberg** [comment]
Please try current master. I now set resolution to 2 for all games that have a game Id starting with 'SCES' or 'SLES'
thanks for reporting this and helping make pop-fe better!

**Comment by HiroTex** [comment]
Thanks, I will!
I'm glad I can be of help, this is a great program and it deserves a lot more attention from the community, I hope we can get a GUI version someday!

**Comment by sahlberg** [comment]
Please have a look at the ps3-gui branch.
It has a very simple app ./pop-fe-ps3.py with a UI to create ps3 packages.
It is very simple and probably does not handle many error conditions properly.
It does not handle audio tracks yet.

But it can always be improved.
