### ISSUE TITLE
Unknown ID: Ace Combat 3 - Electrosphere - Direct Audio with AppenDisc (Japan) - e29d1de18f515145f386abd51e7d4e52

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#101]
Ace Combat 3 - Electrosphere - Direct Audio with AppenDisc (Japan)
e29d1de18f515145f386abd51e7d4e52

**Comment by sahlberg** [comment]
added in
https://github.com/sahlberg/pop-fe/actions/runs/8261235237
