### ISSUE TITLE
Action Replay 2 (USA) (En,Fr,Es,Pt) (Disc 2) (Bonus PSone Codes!) (Unl) - 474eaa0e6adf97aae331f24ed5dfb10b

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#105]
Action Replay 2 (USA) (En,Fr,Es,Pt) (Disc 2) (Bonus PSone Codes!) (Unl)
474eaa0e6adf97aae331f24ed5dfb10b

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262339335
