### ISSUE TITLE
Action Replay 2 V2 (USA) (Disc 2) (Bonus PSone Codes) (Unl) - cdcf7a14dc822dbb4c5ec0f1d6a1908d

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#107]
Action Replay 2 V2 (USA) (Disc 2) (Bonus PSone Codes) (Unl)
cdcf7a14dc822dbb4c5ec0f1d6a1908d

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262339335
