### ISSUE TITLE
Action Replay 2 Version 2.23 (Europe) (En,Fr,De,It) (Disc 2) (Bonus PSone Codes!) (Unl) - 226470cf1b78d6678ef6ab78f8000cc3

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#108]
Action Replay 2 Version 2.23 (Europe) (En,Fr,De,It) (Disc 2) (Bonus PSone Codes!) (Unl)
226470cf1b78d6678ef6ab78f8000cc3

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262339335
