### ISSUE TITLE
Action Replay Ultimate Codes for Final Fantasy Compilation Pack (USA) (Unl) - b2fcbb14ad0a3c96e0497c6cdb81555c

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#111]
Action Replay Ultimate Codes for Final Fantasy Compilation Pack (USA) (Unl)
b2fcbb14ad0a3c96e0497c6cdb81555c

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262339335
