### ISSUE TITLE
A Ressha de Ikou 4 - Evolution (Japan) (Gentei Set) - d2b2230a7a1b058b9098fc4d586460d4

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#112]
A Ressha de Ikou 4 - Evolution (Japan) (Gentei Set)
d2b2230a7a1b058b9098fc4d586460d4

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262448292
