### ISSUE TITLE
A Ressha de Ikou 4 - Evolution (Japan) (Rev 1) - 9aa67185b086b2e2b10fb3b225850414

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#113]
A Ressha de Ikou 4 - Evolution (Japan) (Rev 1)
9aa67185b086b2e2b10fb3b225850414

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8262448292
