### ISSUE TITLE
Addie no Okurimono - To Moze from Addie (Japan) (Demo) - 1704e1fd703d5f2a59c7d6b9a6fffcad

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#115]
Addie no Okurimono - To Moze from Addie (Japan) (Demo)
1704e1fd703d5f2a59c7d6b9a6fffcad

**Comment by sahlberg** [comment]
Fixed in https://github.com/sahlberg/pop-fe/actions/runs/8262577457
