### ISSUE TITLE
Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft (USA) (Demo) - 11a31e432c4d713ad31816e0af7665db

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#118]
Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft (USA) (Demo)
11a31e432c4d713ad31816e0af7665db

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8268260695
