### ISSUE TITLE
Aitakute... - Your Smiles in My Heart - Oroshitate no Diary - Introduction Disc (Japan) - 48a1b00f93da243b370cd3c17bfca18f

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#125]
Aitakute... - Your Smiles in My Heart - Oroshitate no Diary - Introduction Disc (Japan)
48a1b00f93da243b370cd3c17bfca18f

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8268260695
