### ISSUE TITLE
Aitakute... - Your Smiles in My Heart (Japan) - 4 discs not recognised

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#126]
Aitakute... - Your Smiles in My Heart (Japan) (Disc 1)   46dd1b950f4fe3c3a34ac41effe39622
Aitakute... - Your Smiles in My Heart (Japan) (Disc 2)   0a945fa5a5ea5bb4c84c2a1df6f308c5
Aitakute... - Your Smiles in My Heart (Japan) (Disc 3)   a36e3ae1d70bf2802bc1dd7d1e5c3d0a
Aitakute... - Your Smiles in My Heart (Japan) (Disc 4)   c474d063b1b1d26caeae97d9dad3f2e8

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8268260695
