### ISSUE TITLE
Alnam no Tsubasa - Shoujin no Sora no Kanata e (Japan) (Demo) - 02f22a36b78a629ab54aefc408cc8f46

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#131]
Alnam no Tsubasa - Shoujin no Sora no Kanata e (Japan) (Demo)
02f22a36b78a629ab54aefc408cc8f46

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8268260695
