### ISSUE TITLE
Alundra 2 - Mashinka no Nazo (Japan) (Demo) - c26e96bf4bd9d8ffb5f2bf0b40ad43d7

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#132]
Alundra 2 - Mashinka no Nazo (Japan) (Demo)
c26e96bf4bd9d8ffb5f2bf0b40ad43d7

**Comment by sahlberg** [comment]
Added in https://github.com/sahlberg/pop-fe/actions/runs/8268260695
