### ISSUE TITLE
Error making PSX Game

### ISSUE THREAD

**Issue by CrasnadarH** [sahlberg/pop-fe#15]
I was trying to make a pkg of a game called Mizzurna Falls, however it seems to have a problem detecting the game (Concretely, it seems to not reach the id properly). At first I thought that it happened because it was English patched, however I downloaded a correct and unpatched BIN File from somewhere else and had the exact same problem. The game runs fine on an emulator (DuckStation)
How could I fix the issue?

![Screenshot_1](https://user-images.githubusercontent.com/62525264/187309783-5aed3a61-41c5-4909-a74c-6f4beae6e8fe.png)

**Comment by sahlberg** [comment]
There has been recent fixes on how to parse "unusual" entries in SYSTEM.CNF where I read the game-id from.
That should solve the issue you have where the game is misidentified as \\SLP01783  while it should be SLPS01783.

Please try the latest version of pop-fe-ps3 where I have verified that this game now is detected correctly and the pkg builds.

**Comment by CrasnadarH** [comment]
Thank you! Worked like a charm
