### ISSUE TITLE
Erro 2

### ISSUE THREAD

**Issue by KleversonKrash** [sahlberg/pop-fe#16]
Every time I try to create a PSP game, I get the following error [errno 2} "No such file or directory".

How do I resolve this?

Used: [pop-fe-psp

![erro 2](https://user-images.githubusercontent.com/114497101/192547256-ebc1a70b-e8d2-46f4-91ac-9853088ba9de.png)

**Comment by japan1992** [comment]
in the output folder

→psp/games/
create a folder

**Comment by KleversonKrash** [comment]
Same error again

![ERRO](https://user-images.githubusercontent.com/114497101/192850755-d5ef2e7f-fde7-47b5-9005-705f614ae2d8.png)

**Comment by KleversonKrash** [comment]
> 



> in the output folder
> 
> →psp/game/ create a folder

Same error again

I created PSP/GAME too and it didn't work.

> in the output folder
> 
> →psp/game/ create a folder

Same error again

I created PSP/GAME too and it didn't work.

![ERRO](https://user-images.githubusercontent.com/114497101/192853440-f4cd0dd1-95c5-4cbf-8faa-2d3b2dd9f1f1.png)

**Comment by japan1992** [comment]
C:\pop-fe/psp/game/
Set output destination to C:\pop-fe/

**Comment by japan1992** [comment]
You
Set C:\pop-fe/ as the destination folder
Create psp/game folder in C:\pop-fe/
A folder with game id is automatically created in C:\pop-fe/psp/game/ and pbp is converted

**Comment by sahlberg** [comment]
Try to run as administrator?

**Comment by sahlberg** [comment]
The directory you specify must have a pre existing PSP/GAME/ subdirectory.
