### ISSUE TITLE
SkullMonkeys doesn't work on psvita

### ISSUE THREAD

**Issue by holictsubasa** [sahlberg/pop-fe#167]
It exists a fix for this game, but if you convert it with pop-fe, it doesn't include the fix.

**Comment by sahlberg** [comment]
There is a PPF for the US version of SkullMonkeys (SLUS00601) and pop-fe will apply it when you convert it.

I don't know of any PPF files for the PAL versions of this game. If you give me links to PPF files for the PAL versions and if you verify that they work then I can add them to pop-fe.

**Comment by holictsubasa** [comment]
> There is a PPF for the US version of SkullMonkeys (SLUS00601) and pop-fe will apply it when you convert it.
> 
> I don't know of any PPF files for the PAL versions of this game. If you give me links to PPF files for the PAL versions and if you verify that they work then I can add them to pop-fe.

The ppf for US version isn't included on pop-fe folder. I need to patch it manually, since copying the fle into the pppf or in the same folder as the bin/cue files doesn't work. Sorry, I didn't mention the region of the game, but I was refering to the US version

**Comment by sahlberg** [comment]
It should be there.
Make sure you test with the latest build on here:
https://github.com/sahlberg/pop-fe/actions/runs/8547035861

It is not part of an official release yet as I don't make a new release for every change.

**Comment by holictsubasa** [comment]
I see. Thanks a lot, I will close this issue.
