### ISSUE TITLE
Combine Street Fighter Collection (Europe) SLES-00998 Disc 1 and 2

### ISSUE THREAD

**Issue by kalenderfamily** [sahlberg/pop-fe#17]
Really glad I found this tool! Any chance to get Street Fighter Collection (Europe) disc's combined? Kind regards

**Comment by kalenderfamily** [comment]
I saw those ppf files and thought it is supposed to have these specific?

On 15. November 2022 09:20:27 MEZ, Ronnie Sahlberg ***@***.***> wrote:
>What is the issue combining them. What is the error?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sahlberg/pop-fe/issues/17#issuecomment-1314952035
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with Mini Mail. Please excuse my brevity.

**Comment by sahlberg** [comment]
What do you mean?   PPF files are small files that contain small patches to disc images. Usually they are tiny patches for libcrypt protected games.
StreetFighterCollection is not even libcrypt protected. Why would you need a PPF for it?

**Comment by kalenderfamily** [comment]
Oh, ok then my fault! I will try then

On 15. November 2022 11:59:13 MEZ, Ronnie Sahlberg ***@***.***> wrote:
>What do you mean?   PPF files are small files that contain small
>patches to disc images. Usually they are tiny patches for libcrypt
>protected games.
>StreetFighterCollection is not even libcrypt protected. Why would you
>need a PPF for it?
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sahlberg/pop-fe/issues/17#issuecomment-1315142612
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with Mini Mail. Please excuse my brevity.
