### ISSUE TITLE
5th Disc Slot Remains Active (pop-fe PSP)

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#170]
Slot for 5th disc remains active after converting a game with 4 discs.

![image](https://github.com/sahlberg/pop-fe/assets/168254312/f92269fc-0452-4e7e-bb78-8a6076d587b1)

Doesn't cause any issues and is easily corrected by closing and relaunching the tool.

**Comment by sahlberg** [comment]
Fixed in https://github.com/sahlberg/pop-fe/actions/runs/8857406148

**Comment by kirumi0** [comment]
Nice to see the small stuff ironed out too. Great work.
