### ISSUE TITLE
Support for Tales of Destiny 1 & 2 with Spanish patch

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#171]
I've been using the program, and it's been working very well. However, when I try to convert Tales of Destiny with the applied Spanish translation patch, the program doesn't recognize it and gives an error. It also mentions that there's an issue because track 2 is labeled as PREGAP. I've attempted to resolve it by manually editing the CUE file, but it results in another error. Is it possible to address these issues?
I'm providing a link to download the patched game:
https://archive.org/details/psx-compilacion-de-traducciones-en-espanol_202305
There are two versions available, one with the Japanese opening and one without. I've tried both versions, and they both encounter the same error.
It seems that Tales of Destiny II might have the same problem, although I haven't tested it yet.

**Comment by Nanando0** [comment]
pop fe generates an MD5 from each disk.

It will be necessary to correctly post each MD5 generated in the pop fe log related to each game and its disc.

**Comment by sahlberg** [comment]
As @Nanando0 said.
Post the md5 that pop-fe prints and the corresponding disc id for the patched disks and I can add them to the database.

**Comment by AdrCant** [comment]
I've already tested the patched Tales of Destiny 2 and the program recognized it without issues; both versions were recognized. However, it presents the same PREGAP error as Tales of Destiny 1. When converting each track, the following message appears in the log:

Cue2cu2: Warning while processing /*/*/game.cue: The PREGAP command is used for track 2, which requires the software to insert data into the image or disc. This is not supported by Cue2cu2. The pregap will be ignored, and a zero-length pregap will be noted in the CU2 sheet to continue, but the resulting bin/CU2 set might not work as expected or not at all. If possible, please try a Redump compatible version of this image.

**Comment by AdrCant** [comment]
The MD5 checksums for the two versions of Tales of Destiny are as follows:
With Japanese Opening: 6a9cf2aa79bb282048ee0f121c76d488
Without Japanese Opening: e02babf39484755432d988a3d545d312
The ID for the patched versions is as follows (obtained through psx2psp): SLES10626.
It is worth mentioning that the patch is applied to the NTSC-US version of the game.

**Comment by sahlberg** [comment]
SLES10626 must be wrong. SLES is the code for PAL games and not NTSC-U.

Instead, just tell me which game these refers to and I can link them to the right disc:
With Japanese Opening: 6a9cf2aa79bb282048ee0f121c76d488
Without Japanese Opening: e02babf39484755432d988a3d545d312

Are these Tales Of Destiny 1   or 2   is is one of them for TOD1 and the other for TOD2 ?

**Comment by AdrCant** [comment]
> SLES10626 must be wrong. SLES is the code for PAL games and not NTSC-U. (However, the NTSC-U version of Tales Of Destiny is SLUS00626)
> 
> Instead, just tell me which game these refers to and I can link them to the right disc: With Japanese Opening: 6a9cf2aa79bb282048ee0f121c76d488 Without Japanese Opening: e02babf39484755432d988a3d545d312
> 
> Are these Tales Of Destiny 1 or 2 is is one of them for TOD1 and the other for TOD2 ?

Both MD5 files are from Tales of Destiny 1, it's just that the Spanish translation patch allows you to replace the American opening with the Japanese one or keep the American opening.

**Comment by AdrCant** [comment]
> I've already tested the patched Tales of Destiny 2, and the program recognized it without any issues. Both versions were recognized, but it presents the same PREGAP warning as Tales of Destiny 1. When converting each track, the following message appears in the log:
> 
> Cue2cu2: Warning while processing /" "/" "/game.cue: The PREGAP command is used for track 2, which requires the software to insert data into the image or disc. This is not supported by Cue2cu2. The pregap will be ignored, and a zero-length pregap will be noted in the CU2 sheet to continue. However, the resulting bin/CU2 set might not work as expected or not at all. If possible, please try a Redump compatible version of this image.

As I said, Tales of Destiny 2 is recognized by the program but has this warning message when converting track 2 of each disc to AT3. The same thing happens with Tales of Destiny 1.

**Comment by sahlberg** [comment]
I added these md5 so they should be detected as Tales Of Destiny now.

The complaint about pregap I can not do anything about.
This error means that the bin/cue files are bad. Possibly the patch is broken or did not know how to update the cue file correctly?
Don't know. Maybe tell the patch author that it generates a bad cue file.

As for what the effect will be? Hard to say, it could play the CDDA tracks just fine, or there could be issues with the audio.
I think most likely it will work but possibly the audio might be shifted so that it is not synced correctly with the game.
If if it just background music it probably does not matter and is probably not even noticeable if this happens.
If the CDDA tracks are voice audio for cut-scenes then it might be very off-putting and ruin the experience.

If the game converts and the background audio seems fine then you can just ignore this warning that the cue file is bad.
