### ISSUE TITLE
Wrong Logo (PIC0) for Who Wants to Be a Millionaire - 3rd Edition (SCUS94644)

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#172]
The logo coming up for this is for the 2nd Edition instead of 3rd Edition.

Can't say I'm proud of the work but here's a logo I slopped together.

![3rd](https://github.com/sahlberg/pop-fe/assets/168254312/3ac03b0d-fb4b-46de-b26d-44e959f92baf)

**Comment by Nanando0** [comment]
While it is not corrected you can click on PIC0 and switch to the correct image manually.

**Comment by sahlberg** [comment]
That  image is perfect!
Thanks for reporting this and providing a nice image.
I have added the link to the DB and it should be available when this buils completes:
https://github.com/sahlberg/pop-fe/actions/runs/8931638376
