### ISSUE TITLE
Wrong Game Detected - Urban Chaos (SLUS01091)

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#173]
Something is causing the last two digits to get switched. Instead of Urban Chaos (SLUS01091), the disc is detected as Threads of Fate (SLUS01019).

```
MD5 fingerprint 573d7c4f54b9b934e6741d5733c9e611
ID SLUS01019
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/ef435903860fcc15994d23bbe1fa00e9
Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/fdedcf9a64d0582a8914cd29471b4038
```

**Comment by Nanando0** [comment]
> Something is causing the last two digits to get switched. Instead of Urban Chaos (SLUS01091), the disc is detected as Threads of Fate (SLUS01019).
> 
> ```
> MD5 fingerprint 573d7c4f54b9b934e6741d5733c9e611
> ID SLUS01019
> Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/ef435903860fcc15994d23bbe1fa00e9
> Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/fdedcf9a64d0582a8914cd29471b4038
> ```

This is an old problem, and the error is not in the pop fe, the internal code of Urban Chaos is internally wrong. You can see what I'm talking about if you open the .bin image of the game in UltraISO

[SLUS-01091.zip](https://github.com/sahlberg/pop-fe/files/15194590/SLUS-01091.zip)

**Comment by sahlberg** [comment]
Try this build: https://github.com/sahlberg/pop-fe/actions/runs/8931594588

I added the md5 signature to teh database and linked it to the correct disc-id.
Md5 checks override what is specified (int this case incorrectly) in system.cnf

**Comment by sahlberg** [comment]
Verified the detection works correctly now.
