### ISSUE TITLE
NTSC-U games that can not convert CCDA tracks

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#174]
Code snippets below for the following games:

Breath of Fire IV (SLUS01324)
Street Fighter Alpha 2 (SLUS00258)
Street Fighter Alpha 3 (SLUS00821)
Street Fighter Collection [Disc 1] (SLUS00423)

```
DISC SLUS01324
TITLE BREATH OF FIRE IV
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
atracdenc not found.
Can not convert CDDA tracks.
Creating EBOOT.PBP without support for CDDA audio.
Please see README file for how to install atracdenc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Create PBP file at Q:/temp/PSX2PSP/a/SLUS01324/EBOOT.PBP
```

```
DISC SLUS00258
TITLE STREET FIGHTER ALPHA 2
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
atracdenc not found.
Can not convert CDDA tracks.
Creating EBOOT.PBP without support for CDDA audio.
Please see README file for how to install atracdenc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Create PBP file at Q:/temp/PSX2PSP/a/SLUS00258/EBOOT.PBP
```

```
DISC SLUS00821
TITLE STREET FIGHTER ALPHA 3
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
atracdenc not found.
Can not convert CDDA tracks.
Creating EBOOT.PBP without support for CDDA audio.
Please see README file for how to install atracdenc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Create PBP file at Q:/temp/PSX2PSP/a/SLUS00821/EBOOT.PBP
```

```
DISC SLUS00423
TITLE STREET FIGHTER COLLECTION
*SUCCESSFUL TRACK CONVERSIONS OMITTED*
Converting pop-fe-psp-work/TRACK_0_72.wav to pop-fe-psp-work/TRACK_0_72.aea
Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
atracdenc not found.
Can not convert CDDA tracks.
Creating EBOOT.PBP without support for CDDA audio.
Please see README file for how to install atracdenc
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Create PBP file at Q:/temp/PSX2PSP/a/SLUS00423/EBOOT.PBP
```

**Comment by Nanando0** [comment]
These games do not have CDDA, they are dummy files, only the SF Collection has CDDAs, but track 72 is a dummy too.

I think for most of these games the converted EBOOT should work normally, but if in doubt you can modify your .cue files to fix this, open them in a notepad, replace the internal data in the last track:

Where is it:

MODE2/2352

Replace with:

AUDIO

only on the last track.

**Comment by Nanando0** [comment]
> Code snippets below for the following games:
> 
> Breath of Fire IV (SLUS01324) Street Fighter Alpha 2 (SLUS00258) Street Fighter Alpha 3 (SLUS00821) Street Fighter Collection [Disc 1] (SLUS00423)
> 
> ```
> DISC SLUS01324
> TITLE BREATH OF FIRE IV
> Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
> Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> atracdenc not found.
> Can not convert CDDA tracks.
> Creating EBOOT.PBP without support for CDDA audio.
> Please see README file for how to install atracdenc
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Create PBP file at Q:/temp/PSX2PSP/a/SLUS01324/EBOOT.PBP
> ```
> 
> ```
> DISC SLUS00258
> TITLE STREET FIGHTER ALPHA 2
> Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
> Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> atracdenc not found.
> Can not convert CDDA tracks.
> Creating EBOOT.PBP without support for CDDA audio.
> Please see README file for how to install atracdenc
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Create PBP file at Q:/temp/PSX2PSP/a/SLUS00258/EBOOT.PBP
> ```
> 
> ```
> DISC SLUS00821
> TITLE STREET FIGHTER ALPHA 3
> Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
> Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> atracdenc not found.
> Can not convert CDDA tracks.
> Creating EBOOT.PBP without support for CDDA audio.
> Please see README file for how to install atracdenc
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Create PBP file at Q:/temp/PSX2PSP/a/SLUS00821/EBOOT.PBP
> ```
> 
> ```
> DISC SLUS00423
> TITLE STREET FIGHTER COLLECTION
> *SUCCESSFUL TRACK CONVERSIONS OMITTED*
> Converting pop-fe-psp-work/TRACK_0_72.wav to pop-fe-psp-work/TRACK_0_72.aea
> Fatal error: qqq unable to open input file, The byte stream type of the given URL is unsupported.
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> atracdenc not found.
> Can not convert CDDA tracks.
> Creating EBOOT.PBP without support for CDDA audio.
> Please see README file for how to install atracdenc
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Create PBP file at Q:/temp/PSX2PSP/a/SLUS00423/EBOOT.PBP
> ```
These games do not have CDDA, they are dummy files, only the SF Collection has CDDAs, but track 72 is a dummy too.

I think for most of these games the converted EBOOT should work normally, but if in doubt you can modify your .cue files to fix this, open them in a notepad, replace the internal data in the last track:

Where is it:

MODE2/2352

Replace with:

AUDIO

only on the last track.

**Comment by sahlberg** [comment]
The games should play fine but the message is annoying.
Try this version once it builds:
https://github.com/sahlberg/pop-fe/actions/runs/8931934647

Now, when it detects that there are additional data tracks (i.e. not AUDIO) then it will not try to encode them into ATRAC3 format and instead encode the whole disk and all tracks in the disc image section of the EBOOT.
(default is to only encode the very first data track)

**Comment by kirumi0** [comment]
Thanks both for the explanations!

I tried the .cue edit and it worked like a charm.
Tested with the updated pop-fe which also worked like a charm.

@Nanando0 Even though the update has corrected this, for curiosity is there a way to tell these games don't have CDDA or did you know from the error in the logs?
