### ISSUE TITLE
Wrong Logo for Bravo Air Race NTSC-U

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#178]
This is one of those games that have different naming and assets in different regions. The logo for the PAL version (Air Race) is being used instead of the NTSC-U version (Bravo Air Race).

All 3 logos here:
https://gamesdb.launchbox-app.com/games/images/11777-bravo-air-race

**Comment by sahlberg** [comment]
Awesome. thanks!

Should be fixed in this build:  https://github.com/sahlberg/pop-fe/actions/runs/9145507004

**Comment by kirumi0** [comment]
I found another but I'll hold off and make a list instead of making a post per game.
