### ISSUE TITLE
Brunswick Circuit Pro Bowling 2 NTSC-U Black Screen

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#179]
The EBOOT from pop-fe doesn't go past the Playstation boot logo on Adrenaline (Vita), it stays on a black screen and the Vita goes to sleep if you wait long enough. It's also not recognized by Duckstation on Windows and likely no other system (can't confirm).

The EBOOT downloaded from a certain top Google result is recognized and playable in Duckstation (possibly other systems too) but behaves the same as pop-fe's EBOOT on Adrenaline.

The PSX2PSP sheet notes "_x (CDDA) Game locks before title screen_", so Adrenaline is likely out of the question at least.
https://docs.google.com/spreadsheets/d/13TRadnKyoOjzpxzMeVrO8adzbRNWccr5

**Comment by Nanando0** [comment]
cmd: 0x00 val: 0x07 or ID SLPS01156 boot in game, but the game crashes when starting the bowling game.

**Comment by sahlberg** [comment]
Please ask at https://gbatemp.net/threads/pops-on-psp-vita-config-research.607286/page-65
that is where all the people working on configs for psp/vita hang out.

It might be that your game needs a config and those folks might be able to help.
