### ISSUE TITLE
[Request] POP-FE PSP & PS3

### ISSUE THREAD

**Issue by mikesierra85** [sahlberg/pop-fe#20]
1- Is it possible not to add the game's name and ID on PIC1.PNG as a watermark when the game file is created?
2- Is it possible to add an option for a custom BOOT.PNG the same way as older tools like PSX2PSP offered rather than the POPS Loader splash?
3- Is it possible to allow custom PSP and PS3 sized ICON0.PNG (144x80 for PSP and 320x176 for PS3? Adding a custom picture with those resolutions always squashes it to the default squared shape.

Thank you

**Comment by sahlberg** [comment]
1, I have added options for watermark creation to pop-fe (--watermark) and pop-fe-psp (a checkbox in the ui) to control whether this watermark will be generated. Please test it out on current master branch.

3, I have added options for whether iCON0 should be square for pop-fe (--square-icon0) and pop-fe-psp/pop-fe-ps3 (a checkbox in the ui) to control whether it should be made square or it should be scaled to the native resolution.
Please test this if it works. I have only done very very light testing on it.

2,  I don't know how to do this. Do you have links to psx-place or similar where there is a technical description on how to change this?  If so I can implement it.

**Comment by sahlberg** [comment]
On Mon, 21 Nov 2022 at 18:48, mikesierra85 ***@***.***> wrote:

> I'm not sure if I'm doing this right or not, I downloaded
> pop-fe-master.zip and extracted the content inside the folder that I have
> from the 0.0.14 release, overwritten the files. I can see the new options
> in the UI.
> I am still getting a square ICON0.PNG and watermark in PIC1.PNG for PSP.
>
Did you download and extract the artefact at the bottom of this page ?
https://github.com/sahlberg/pop-fe/actions/runs/3506220838

It is the link called pop-fe-ui

When you run pop-fe-psp in this package,   untick the box called
"watermark" if you don't want the watermark.
Tick the box 'Rescale ICON0 to square' if you want it to be square, untick
it if you want it to be scaled to  144x80


I couldn't find info regarding the BOOT.PNG file option that PSX2PSP uses
> I'm afraid.
>

No worries. I will track it down and implement it.  Will take some time
before I get time for it.

**Comment by mikesierra85** [comment]
I downloaded the file you mentioned, it's all working perfectly, thank you very much.

I am looking forward to future updates, keep up the good work. much appreciated.
