### ISSUE TITLE
Vib-Ribbon NTSC

### ISSUE THREAD

**Issue by Quebrandosistema** [sahlberg/pop-fe#204]
MD5 beb515901781c14bbe2991a20ff7388e

SCUS-02873

Vib-Ribbon NTSC

**Comment by Quebrandosistema** [comment]
For the PSP and Vita, you won't need an MD5 for the mod if the original SLES with force is even better.
Topic close.

**Comment by sahlberg** [comment]
I just added this entry in the database anyway.  Doesn't hurt.
