### ISSUE TITLE
Support for AT3 and PAM files

### ISSUE THREAD

**Issue by HNKMaster** [sahlberg/pop-fe#207]
I feel that an option to add .at3 and .pam files would be nice, since there's methods to make custom media for those formats, and for PSP the only way to add them is by making another EBOOT.PBP with the new file using PSP Content Manager. With PS3 is even less straightforward because of the harder way to edit PKG files. I feel it could be good to add it as an option.

**Comment by sahlberg** [comment]
There is already support for AT3 files and it will convert CDDA into AT3 as well as any youtube link that is provided as SND0.

PAM is more difficult because there are no available tools to create them. Only tools that can do PAM are proprietary internal SONY tools.  So we can not do PAM.

**Comment by HNKMaster** [comment]
No way to add already premade ones? For example for SND0 audio that contains a loop point and stuff like that.

**Comment by sahlberg** [comment]
Yes, just point to the file using the --snd0 command line argument and it will convert it to AT3 and install it.

Closing as already implemented.
