### ISSUE TITLE
Alternate Edition Assets

### ISSUE THREAD

**Issue by kirumi0** [sahlberg/pop-fe#214]
Some games such as [Jet Moto 2](https://gamesdb.launchbox-app.com/games/images/980-jet-moto-2) and [The Lost World - Jurassic Park](https://gamesdb.launchbox-app.com/games/images/13088-the-lost-world-jurassic-park) have an alternate edition ([here](https://gamesdb.launchbox-app.com/games/images/113434-jet-moto-2-championship-edition) and [here](https://gamesdb.launchbox-app.com/games/images/73428-the-lost-world-jurassic-park-special-edition)), which have the same game ID as the original.
Is there a way to make pop-fe tell the difference and use the correct assets if added to the database?

**Comment by sahlberg** [comment]
Yes. It requires a little effort but not too much. Sometimes.
If they have different content but the same disc-id then we can detect which version of the disc it is.
If the content on the disks are different, then there is not much we can do.

Try to convert both versions and check what the 'MD5 fingerprint' is.
Pop-fe will print this to the console when you convert it.

If the two versions of the disk have different MD5 fingerprints then we can do it.

The way to do it then is by creating a new entry for the other version of Jet Moto 2 with a different made-up disc-id.

For example the current one has:
    'SCUS94167': {
        'url': "games/U/J/SCUS-94167.html",
    	'id': 'SCUS94167',
	'title': "JET MOTO 2",
        ...

So create a second entry with a different id like this:
    'SDUS94167': {
        'url': "games/U/J/SCUS-94167.html",
    	'id': 'SCUS94167',
	'title': "JET MOTO 2",
        ...

Then down in the section:
gameid_by_md5sum = {

 Create two new entries, one for each of the two md5 fingerprints and have them reference the appropriate 
SCUS.. or SDUS..  entry above.

**Comment by sahlberg** [comment]
For Jet Moto 2, I assume you are refering to these two versions of it:
http://redump.org/disc/15409/
http://redump.org/disc/6729/

From that it looks like Track 1, the data track, has different content of the two versions so this procedure I described above should work for pop-fe.
Note that redump.org and pop-fe has different md5 fingerprints.  Redump computes the md5 for the whole track while pop-fe only computes if over the first 1MByte of the track (for performance reasons)

**Comment by sahlberg** [comment]
I merged the PR you sent with the updated assets.
