### ISSUE TITLE
Converted Racing lagoon (Pop-fe psp) Corrupted

### ISSUE THREAD

**Issue by Yessirballs** [sahlberg/pop-fe#215]
Hello when i converted and transfered my copy of racing lagoon on my psp it says its unable to boot becuase its corrupted yes i tested the disk file before converting it works I even asked a friend to try converting and booting up on his psp he said it does not work he thinks its the config for racing lagoon thats making it corrupted

**Comment by sahlberg** [comment]
I converted the japaneese version of this game and iit booted and I started the first race. It seemed to work fine on my PSP.

If you think something is wrong with the CONFIG,  please ask on this thread:
https://gbatemp.net/threads/pops-on-psp-vita-config-research.607286/page-64

That thread is where most of the people that work on and develop configs hang out.

**Comment by Yessirballs** [comment]
> I converted the japaneese version of this game and iit booted and I started the first race. It seemed to work fine on my PSP.
> 
> If you think something is wrong with the CONFIG, please ask on this thread: https://gbatemp.net/threads/pops-on-psp-vita-config-research.607286/page-64
> 
> That thread is where most of the people that work on and develop configs hang out.

Hello its me did you converted it with the config in mind? If yes do you know why its showing an error saying its corrupted?

**Comment by Yessirballs** [comment]
Hello you can close this issue i found out whats cuasing it its becuase im using an Racing lagoon (japan,asian) the only version that got an english patch
