### ISSUE TITLE
Racing Lagoon Just corrupts when converting on the latest Version of Pop-fe

### ISSUE THREAD

**Issue by Yessirballs** [sahlberg/pop-fe#218]
Hello i finally converted Racing lagoon it with pop-fe but i converted it with an old version of pop-fe the July 21 version (1.12) I think the lastest version (1.14) on windows just bugs racing lagoon that it just made it corrupts when converting and it wont work on psp pls fix this in the future
I only know that when i converted it on the july 21 version (1.12) it works but not on the lastest version (1.14) of Pop-fe windows

**Comment by kirumi0** [comment]
I've hit the same issue with Jet Moto 2 (standard version, Championship Edition doesn't have this issue) so this could be affecting quite a few games.

The game runs fine in Adrenaline (Vita) when using the v1.14 release but more recent builds under the Actions tab in GitHub give the error below on Adrenaline.
"_This game cannot be started.
The data is corrupted._"

The EBOOT that doesn't run in Adrenaline also isn't recognized at all by Duckstation on Windows but the good version is and boots fine.

**Comment by Yessirballs** [comment]
![IMG_0178](https://github.com/user-attachments/assets/b746c4e0-e11c-4eaf-98b3-770c2d88dc80)
How weird

**Comment by Yessirballs** [comment]
> Did a bit of testing and found where some games broke (before seeing the above post).
> 
> Racing Lagoon [SLPS02038] became corrupted in [Action #713](https://github.com/sahlberg/pop-fe/actions/runs/10233903437) Jet Moto 2 [SCUS94167] (not Championship Edition) became corrupted in [Action #721](https://github.com/sahlberg/pop-fe/actions/runs/10420571004) MediEvil II [SCUS94564] became corrupted in [Action #713](https://github.com/sahlberg/pop-fe/actions/runs/10233903437)

Try disabling or raplacing  pic0/pic1

**Comment by sahlberg** [comment]
kirumio, this is good information ans something I can try to track down.
I will have a look at this tomorrow.

Are you using windows or linux?  I do not have access to any windows machines so ...   hopefully it can reproduce on linux.

**Comment by Yessirballs** [comment]
> kirumio, this is good information ans something I can try to track down. I will have a look at this tomorrow.
> 
> Are you using windows or linux? I do not have access to any windows machines so ... hopefully it can reproduce on linux.

Im using windows

**Comment by kirumi0** [comment]
> Are you using windows or linux?

I'm on Windows.

**Comment by sahlberg** [comment]
Please test the most recent release. 
For now I default to not skip the PSTITLEIMG section in the EBOOT, which I suspect cased some mis-alignment.
This should make things work until I can figure out what the issue is with no-pstitleimg section for these games are.
I bet it is some kind of alignment issue to where the psisoimg section is supposed to start at.

**Comment by kirumi0** [comment]
I tested all 3 games and they all booted on [Action 731](https://github.com/sahlberg/pop-fe/actions/runs/10545403183). Looks like you're right about the issue.
