### ISSUE TITLE
98demake themes not working on supported games

### ISSUE THREAD

**Issue by deadlyjunk** [sahlberg/pop-fe#22]

**Comment by sahlberg** [comment]
Do you have a description or example to reproduce?
The theme only supports ~70 games so far but is actively expanded.
Maybe you can help add some games to the theme once we sort out this current issue you have?

**Comment by deadlyjunk** [comment]
tried driver 1 slus00842
it kept giving me the normal theme even after picking the 98demake one
Fetching SND0


Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/SND0.WAV?raw=true
Get icon0 from theme
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/ICON0.PNG?raw=true
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/ICON0.png?raw=true
Try URL http://www.hwc.nat.cu/psx/SLUS_008.42_COV.jpg
Falling back to PSXDATACENTRE for cover
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/PIC0.PNG?raw=true
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/PIC0.png?raw=true
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/PIC1.PNG?raw=true
Try URL https://github.com/98DEMAKE/pop-fe-theme-98demake/blob/main/data/SLUS00842/PIC1.png?raw=true


even after it checking for the 98demake theme it kept falling back for me

**Comment by sahlberg** [comment]
Ok, let me have a look in a couple of days. I am off to a roadtrip with limited internet access but will look at this in two/three days. Please remind me if I forget.

**Comment by sahlberg** [comment]
Please try the latest v1.0.4
It seems like windows and wget.exe did not like certain paths so it would never download the assets.
I rewrite it using requests.get() instead.

Oh Windows,  why can't you work like Unix does?

**Comment by sahlberg** [comment]
fixed.
