### ISSUE TITLE
Support for Ace Combat 3: Electrosphere - Direct Audio with AppenDisc (SLPM-80453)

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#220]
Hello, I would like to inquire if it would be possible to add support for the AppenDisc of the game Ace Combat 3: Electrosphere (ID SLPM-80453), a special disc that was only released in Japan and includes special content for the Japanese version of the game (a sort of third disc for the original game, which has 2 discs). A translation patch into English, Spanish, and Italian has been released for both the game and the AppenDisc. Adding support for it would allow for the complete experience of the game as it was originally conceived.
Link to the patch site with more information: https://loadwordteam.com/projects/ace-combat-3-electrosphere-a-complete-fan-translation/

**Comment by sahlberg** [comment]
Absolutely. No problem.

I added it to the database and it will be available in https://github.com/sahlberg/pop-fe/actions/runs/10706826699
when it finishes building.
I gave it the same graphics assets as the first disc, let me know if you would rather want different pic0/pic1.

**Comment by sahlberg** [comment]
I can add the patched disk images too.
What I need to do that is for you to send me the md5sum for the disk that pop-fe prints when it processes the disk.

I would need it in this format (example)
SLES-12345
Ace Combat 3 Electrosphere Disk 1 Spanish
md5: abcde.....

I.e. the disc id,   the name you want pop-fe to give it, and the md5sum that pop-fe prints when it processes the disks.

The MD5 looks something like this:
MD5 fingerprint 2ef2b4d005404aa957d37dc625f158e6

**Comment by sahlberg** [comment]
I.e. I added the japaneese version to teh database.  To add the translations to the database I need the md5 fingerprint for them.

**Comment by sahlberg** [comment]
I think all the translations are detected now and work.
