### ISSUE TITLE
Disable --snd0 using pop-fe.exe

### ISSUE THREAD

**Issue by HNKMaster** [sahlberg/pop-fe#221]
I'm using the pop-fe.exe version to convert games by command line, but sometimes I want my game without some stuff, like not adding a SND0.at3 to it. For some reason I can't disable the automatic SND0, even removing the "--snd0" option, and I've tried "none", "false" and "null", but it triggers an error everytime. The documentation doesn't say how to skip this option, so I ask here please.

EDIT: I found the "--force-no-assets" option after reading the code, this managed to disable SND0 when I removed it. The readme lacks this bit on the documentation.

**Comment by sahlberg** [comment]
Sorry about that.   The --force-no-assets is not documented as it was really just intended to help me when testing things and I don't want to spend time waiting for assets to download.

But yes, being able to disable snd0 is useful.
I have pushed a small change to master that allows you to disable snd0 by using
  --snd0=no

Thanks for the suggestion
