### ISSUE TITLE
Auto Install misses PSL1GHT pkgcrypt module

### ISSUE THREAD

**Issue by sremp** [sahlberg/pop-fe#222]
The `install_deps()` function checks for PSL1GHT by doing a stat on the `PSL1GHT` directory:

```python
        # PSL1GHT
        try:
            os.stat('PSL1GHT')
            print('PSL1GHT is already installed')
        except:
            print('Cloning PSL1GHT')
            subprocess.call(['git', 'clone', 'http://github.com/sahlberg/PSL1GHT'])
            os.chdir('PSL1GHT/tools/ps3py')
            subprocess.call(['git', 'checkout', 'origin/use-python3'])
            subprocess.call(['make'])
            os.chdir('../../..')
```

The tools are bundled as submodules, so this will succeed. However, the pkgcrypt module is not included in the repo, and due to the check above, it does not get compiled. This results in a `ModuleNotFoundError` when running pop-fe:

```
$git clone git@github.com:sremp/pop-fe.git --recursive
$ cd pop-fe
$ ./pop-fe.py --install
Install/Update required dependencies
...
PSL1GHT is already installed
$ ./pop-fe.py --ps3-pkg=Castlevania-SotN.pkg Castlevania.cue 
Processing Castlevania
...
Create ISO.BIN.EDAT
Create PKG
Traceback (most recent call last):
  File "/home/anvil/pop-fe/PSL1GHT/tools/ps3py/pkg.py", line 219, in <module>
    import pkgcrypt
ModuleNotFoundError: No module named 'pkgcrypt'
Finished. Castlevania-SotN.pkg created
```
Have not tried installing the PKG on a PS3 but suspect the game will be unplayable. 

Fixes are either install `pkgcrypt` manually or add logic to check for the module in `PSL1GHT/tools/ps3py`. I made this [change](https://github.com/sremp/pop-fe/commit/4d41d5df6e7ba0b6b050a7f7d2cee9374fc5755b) in my forked repo, tested it and it seems to work well enough.

**Comment by Fabxx** [comment]
can confirm on debian 12 as well, the dependency is not installed. I tried to install it from pip3 install but the library is not found

**Comment by sahlberg** [comment]
Try the current master branch.

It was missing a 'git submodule update --init'
