### ISSUE TITLE
.CHD format crashing

### ISSUE THREAD

**Issue by sim-muskit** [sahlberg/pop-fe#227]
Hi, I'm trying to use .chd format to create an eboot, but the  crashes immediately upon trying to load the .chd. Could I ask for some help please?

**Comment by sahlberg** [comment]
What is the error message in the console window?
Do you have chdman installed?

**Comment by sim-muskit** [comment]
That's the thing, I don't get a chance to read the GUI (pop-fe-psp) just closes the moment I attempt to load a .chd into the disk

**Comment by sahlberg** [comment]
Open a command window and then run pop-fe-ps3.exe from the command line.

**Comment by sim-muskit** [comment]
Still no luck, tried both pop-fe-psp and pop-fe-ps3 through cmd and they opened up, but once I attempted to load a chd, they both crashed.

**Comment by sahlberg** [comment]
Pop-fe does not include  chdman.exe  and will abort if this executable is not found.
Can you try downloading chdman and installing chdman.exe in the same directory as you have pop-fe?

**Comment by sim-muskit** [comment]
It was as you said. All I needed to do was make a copy of chdman.exe in the pop-fe-ui directory and it worked like a charm. Thank you for the suggestion!

**Comment by sahlberg** [comment]
Great!
Ok, I will update the build on saturday and have it include chdman.exe in pop-fe-ui.zip
