### ISSUE TITLE
Fails To Pull Game ID

### ISSUE THREAD

**Issue by billtookahit420** [sahlberg/pop-fe#23]
Fails to convert game "rayman" worked on very first release:
[INFO]  Opening cue: G:\Retro Roms\Sony Playstation\Rayman (USA)\Rayman (USA).cue
[INFO]  Merging 51 tracks...
[INFO]  Wrote C:\Users\billt\Desktop\pop-fe-ui(5)\pop-fe-ps3-work\MBd1.bin
[INFO]  Wrote new cue: C:\Users\billt\Desktop\pop-fe-ui(5)\pop-fe-ps3-work\MBd1.cue
ID SLUS-00005
Fetching SND0
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 237, in on_path_changed
KeyError: 'SLUS-00005'

Fails to pulls game id for the game "D":
[INFO]  Opening cue: G:\Retro Roms\Sony Playstation\D (USA) (Disc 1)\D (USA) (Disc 1).cue
[INFO]  Merging 3 tracks...
[INFO]  Wrote C:\Users\billt\Desktop\pop-fe-ui(5)\pop-fe-ps3-work\MBd1.bin
[INFO]  Wrote new cue: C:\Users\billt\Desktop\pop-fe-ui(5)\pop-fe-ps3-work\MBd1.cue
ID NSTACK=
Fetching SND0
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 237, in on_path_changed
KeyError: 'NSTACK='

I also can replicate the same issue in linux as well

**Comment by sahlberg** [comment]
It was an issue with parsing of system.cnf
This file does not have a standard format and Raman used yet another varient of how it wrote the game id.

This is fixed in master as well as the v1.0.5 release for windows.
Make sure to activate the 98DEMAKE theme. It have very nice assets for this title.

**Comment by billtookahit420** [comment]
thank you very much keep up the hard work
