### ISSUE TITLE
Errors when creating multidisc eboot [Docker]

### ISSUE THREAD

**Issue by ghost** [sahlberg/pop-fe#26]
> pop-fe.py --psp-dir=/psp/ /psp/game.cue /psp/game2.cue /psp/game3.cue /psp/game4.cue
> Processing /psp/game.cue ...
> Processing /psp/game2.cue ...
> Processing /psp/game3.cue ...
> Processing /psp/game4.cue ...
> Try URL http://www.hwc.nat.cu/psx/SCES_030.46_COV.jpg
> Id: SCES03046
> Title: THE LEGEND OF DRAGOON
> Create PBP file at /psp//PSP/GAME/SCES03046/EBOOT.PBP
> Traceback (most recent call last):
>   File "/pop-fe/pop-fe.py", line 2036, in <module>
>     create_psp(args.psp_dir, disc_ids, game_title, icon0, pic0, pic1, cue_files, cu2_files, img_files, mem_cards, aea_files, snd0=snd0, watermark=args.watermark, subchannels=subchannels)
>   File "/pop-fe/pop-fe.py", line 777, in create_psp
>     generate_pbp(dest_file, disc_ids, game_title, icon0, pic0, pic1, cue_files, cu2_files, img_files, aea_files, snd0=snd0_data, whole_disk=False, subchannels=subchannels)
>   File "/pop-fe/pop-fe.py", line 719, in generate_pbp
>     p.create_pbp()
>   File "/pop-fe/popstation.py", line 3169, in create_pbp
>     self.encode_psiso(fh, disc_num, img_toc)
>   File "/pop-fe/popstation.py", line 2700, in encode_psiso
>     isosize = self._track0_size[disc_num]
> IndexError: list index out of range

The incomplete eboot does not start. (corrupted file)

**Comment by sahlberg** [comment]
Try current master. I have checked in a fix for this that should solve it.
