### ISSUE TITLE
Modifying current retroarch support

### ISSUE THREAD

**Issue by rhynec** [sahlberg/pop-fe#3]
The current retroarch installation implemented in pop-fe, from what I understand, merges each bin file with binmerge and generates and appropriate .m3u file to load them as multiple discs. However, isn't the cue information lost in this procedure? According to retropie [wiki](https://retropie.org.uk/docs/Playstation-1/), m3u files should be able to load cue files instead of bin files. So, perhaps for pop-fe, the retroarch installation could also copy over the cue files named with the game title but with the extensions CD1/CD2/etc (or named the same as their respective img/bin files with the CD# extension as well). Perhaps there could also be the option to create a folder with the game's official title in the given retroarch directory, so that each m3u/img/cd# combo for each game is easier to organize when running a script using pop-fe.py

And, given that most (all?) cores in retroarch are able to load pbp files, maybe there could also be an option to generate them in the given retroarch dir as well (named [title].pbp instead of eboot.pbp, or inside a folder with the title_id/title, depending on how retroarch expects the name of the pbp file to be). Currently tricking pop-fe into generating the pbp files for the PSP doesn't work very cleanly since it assumes the PSP/GAME directories exist inside the given --psp-dir folder (I patched it by switching the mkdir function for the makedirs function in the create_retroarch function).

**Comment by sahlberg** [comment]
Absolutely.   I don't use retroacrh much/at all so it has not had the same TLC that the PS3 and PSP has got.
I think your suggestions would be great, especially If retroarch can use PBP files, since that would save a lot of moving files about.

Do you want to implement this and send a pull request?

**Comment by rhynec** [comment]
I'll give it a go. Feel free to clean-up what I submit any way you wish (it's been a while since I've used Python).

**Comment by rhynec** [comment]
Alright! Patches and documentation finished, so I'll close this issue.
