### ISSUE TITLE
Error making multidisc PKG from PSX games

### ISSUE THREAD

**Issue by rafa931** [sahlberg/pop-fe#30]
i got and error converting multidisc games to pkg , I already tried this games The Legend of Dragoon 4 discs, Metal Gear Solid 2 discs, Final Fantasy VII 3 discs. I have to say that these game versions are the Spanish ones. This is the error am getting
![photo_2023-05-09_00-07-07](https://user-images.githubusercontent.com/72876031/236991418-2bd0ee08-d676-4fe6-b54d-51215ad5e9e7.jpg)

**Comment by sahlberg** [comment]
It works here both on linux and windows.

The error you see is from PKG.EXE which comes from PSL1GH, the development kit for PSX.
It could either be a bug in PKG.EXE or maybe it just runs out of memory.
How much memory do you have in the PC and which version of windows is it?

What pop-fe tries to do here is just run PKG.EXE to create a package.
The commandline is something like this :

pkg.exe -c UP9000-SLES01734_00-0000000000000001' pop-fe-ps3-work\SLES01734 game.pkg

Try to run this manually from the directory where POP-FE is installed after it has crashed like this.
If that fails too, open a bug with PSL1GHT (which also has a git-hub page).

A workaround would be to manually install the game on the PS3, skipping the PKG step.
After it has crashed like this, the game directory will be in pop-fe-ps3-work\SLES01734
Copy the SLES01734 directory to /dev/hdd0/game   on your PS3 and that should work too.

**Comment by sahlberg** [comment]
Closing as nothing further to debug
