### ISSUE TITLE
Error when trying to create a new pkg

### ISSUE THREAD

**Issue by Raziel-LaFey** [sahlberg/pop-fe#31]
![image](https://github.com/sahlberg/pop-fe/assets/91440123/0523904c-4aee-48d6-8d71-8825f9048711)

**Comment by sahlberg** [comment]
Hmmm.   seems requests_cache might have become broken on windows in recent builds. I have removed the requests cache dependency for now.

Please try the latest release.

**Comment by sahlberg** [comment]
Closing as this should be fixed in current release and no feedback
