### ISSUE TITLE
Error when creating pbp for psp/vita

### ISSUE THREAD

**Issue by Danker1990** [sahlberg/pop-fe#32]
keep trying to create an image and this error keeps being spat out on Windows 11

Creating EBOOT
DISC SLES01937
TITLE 40 WINKS - CONQUER YOUR DREAMS
Scanning for audio tracks
Create PBP file at C:/Users/danny/Desktop/Vita/PSP/GAME/SLES01937/EBOOT.PBP
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 490, in on_create_eboot
  File "pop-fe.py", line 882, in create_psp
  File "pop-fe.py", line 824, in generate_pbp
  File "popstation.py", line 3093, in create_pbp
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/danny/Desktop/Vita/PSP/GAME/SLES01937/EBOOT.PBP'

**Comment by sahlberg** [comment]
You need to create this directory : C:/Users/danny/Desktop/Vita/PSP/GAME/

If you connect a PSP/Vita with USB, it will show up as a drive letter and there will always be a PSP/GAME subdirectory where the games will be installed.   I don't automatically create the directories PSP and PSP/GAME as if you select a drive letter and these direcotries are missing, it probably means you selected the wrong drive and not the PSP/VITA.

If you just want to create EBOOTS and store them locally on your computer, like you are trying to do, then you need to manually create PSP/GAME.

**Comment by Danker1990** [comment]
this might be a bit of info needed to be added in the readme as had to do alot of trial and error prior to your message. only after i worked it out myself did this come through.

**Comment by sahlberg** [comment]
I think you are right. I will spend some time today or tomorrow to think about how to improve this.
In my defense, I originally only used it to create EBOOTs and write them directory to a USB connected PSP
but I think I need to improve the other usecases too, like yours, when writing them to just some directory on the local harddrive.

**Comment by sahlberg** [comment]
I have simply removed the requirement for PSP/GAME to exist. IF this directory exists then it is assumed we have a PSP or a Vita and then we will create the game in PSP/GAME/disk-id/EBOOT.PBP
If it doesn't exist then instead of failing we will instead create the game directly udner disk-id/EBOOT.PBP

Please try the latest build with this change with the build artefacts from https://github.com/sahlberg/pop-fe/actions/runs/5766834495

Thanks for reporting this so I could fix it.
