### ISSUE TITLE
[Suggestion] CHD conversion support?

### ISSUE THREAD

**Issue by ParzivalWolfram** [sahlberg/pop-fe#35]
As the CHD format is superior for holding CD-based titles (especially multi-track or multi-disc titles), and is used heavily in MAME and a few other emulators, it would likely be worth it to add support for these to the tool. On Debian, at least, you can find a chd converter, `chdman`, under the `mame-tools` package. I've also written a shell script for my own use in conversion, as it's a two-line affair with bchunk and chdman:

```
chdman extractcd -f -i "$1" -ob /tmp/tmp.bin -o /tmp/tmp.cue
bchunk /tmp/tmp.bin /tmp/tmp.cue "$2"
```

**Comment by sahlberg** [comment]
Please try current master. It will try to extract and use the cue/bin from a CHD file IF the chdman binary is available.
Only supported got pop-fe but not yet pop-fe-psp or pop-fe-ps3

**Comment by ParzivalWolfram** [comment]
Thanks, this worked. I can use CHDs just fine now.
