### ISSUE TITLE
[Suggestion] Handle passing in a pre-made AT3

### ISSUE THREAD

**Issue by ParzivalWolfram** [sahlberg/pop-fe#36]
The current code does not handle pulling in a pre-converted AT3 file, and will try to re-encode it. As these were required for custom sounds in the past, it would be beneficial to check if a re-encode is necessary in the first place for those trying to use pre-made files.

**Comment by sahlberg** [comment]
Can you give the latest master a try?
I have added some basic conditionals to just use the snd0 file as-is without any conversion if it looks like it is in at3 format but have not had much time to test properly.

**Comment by ParzivalWolfram** [comment]
This didn't work, my AT3s are still re-encoded again. I don't see any output to give to clarify the issue, unfortunately.

**Comment by sahlberg** [comment]
When you say AT3, do you mean the SND0 that is played on the XMB when the game is selected?
Or do you mean the in-game CD-DA audio tracks?

**Comment by ParzivalWolfram** [comment]
The passed-in SND0 file, apologies.

**Comment by sahlberg** [comment]
It might be the detection of "is this already AT3" that is failing. I made the detection based on how the files created by atracdenc and similar works.
Can you send me a short file that you use and I can look at how to detect it as already processed correctly.

**Comment by ParzivalWolfram** [comment]
[out.at3.tar.gz](https://github.com/sahlberg/pop-fe/files/12403576/out.at3.tar.gz)
Produced using https://www.modconsoles.fr/club-articles.html/pc/at9at3-converter-v23-r36 forever ago, though I think it was an older revision.

**Comment by sahlberg** [comment]
And that file, you just add it as SND0.AT3 to the games directory and it will play?
I will have a look at this on saturday or sunday.

**Comment by ParzivalWolfram** [comment]
I think PSX2PSP bakes it into the EBOOT, but it plays just fine on the XMB menu in either case, yes.

**Comment by sahlberg** [comment]
Can you try current master?
I loosened up the check for compression_code to allow your file to be
accepted as valid.
Looking at the code value I am not sure that your file is even at3   but
whatever, it should allow your file now as is

**Comment by sahlberg** [comment]
resolved
