### ISSUE TITLE
[Suggestion] Disable PIC1, PIC0 and music on pop-fe-ps3.exe

### ISSUE THREAD

**Issue by ewertonpires2** [sahlberg/pop-fe#37]
Just a suggestion. Sometimes there's no cool background to add and we prefer to disable the backgrounds pics and use the PlayStation 3 XMB theme. When I try to disable the PIC1 appears the back cover picture and it's annoying. It would be nice if possible to create the PS3 PSN art with ESRB Content Rating (like the PSP eboot PSN art).

**Comment by sahlberg** [comment]
Please try the artefacts in the latest build :  https://github.com/sahlberg/pop-fe/actions/runs/5915817293
it contains a "disable pic1" button now in pop-fe-ps3

**Comment by ewertonpires2** [comment]
I was searching for some cool picture for Fighting Force 2 game, but all the images are in low quality or there's no interesting wallpaper to apply to the background. 
For ESBR content you can search in this site : https://www.esrb.org/search/

There's also this article, but I think that it's for PSP version, but it's the same used in the PS3 PSN: https://www.nextgenroms.com/topic/4622-mattiams-psx2psp-eboot-collection/

**Comment by sahlberg** [comment]
resolved
