### ISSUE TITLE
BIN/CUE, BIN (track) y BIN no se ejecutan bien en RE2 PAL Spain

### ISSUE THREAD

**Issue by AlejandroMetheny** [sahlberg/pop-fe#38]
Un dato por si ayuda a la mejora de pop-fe. Probe convertir Resident Evil 2 PAL (spain) con BIN en modo multi disco, y solo ejecuta la introducción y el menu principal, pero no el gameplay, aparece la pantalla en negro y sin audio. Lo mismo sucede si lo hago por discos separados. Probe también con un Resident Evil 2 PAL (spain) con BIN (track1)/BIN (track2) y sucede lo mismo. Probe otro igual con BIN/CUE, pero el audio y las voces del gameplay se oyen distorsionadas. Con juegos como Resident Evil Director's Cut BIN PAL y Resident Evil 3 Nemesis BIN PAL (Spain) la conversión, el gameplay y el audio corren muy bien.

**Comment by sahlberg** [comment]
Can you tell the the disc id for the discs that are failing and I will try to reproduce.

**Comment by sahlberg** [comment]
Please try the version of pop-fe-ps3 on this page:
https://github.com/sahlberg/pop-fe/actions/runs/6081132085

It contains a config that modifies RE2 PAL Spain. It might solve the issue you have.

**Comment by sahlberg** [comment]
Please try the latest release of pop-fe
