### ISSUE TITLE
PSP GUI possible Bug + Misc

### ISSUE THREAD

**Issue by wad11656** [sahlberg/pop-fe#43]
![image](https://github.com/sahlberg/pop-fe/assets/85006632/06ce98f1-3cb3-4d45-adad-69db77349448)

pop-fe PSP:

1. I don't think changing the GameID field changes the GameID.
2. When EBOOT is finished being created, it says "PKG" instead of "EBOOT" (Who cares but just fyi)
3. Does the "Theme" affect anything in the PSP version? If so, can you make it show you a live preview when you select a theme?
4. After a random PIC1 is pulled from psxdatacenter, can you add the ability to click the PIC1 thumbnail to cycle through the different options?

Thank you, this is nifty and super surprising that it exists

P.S. I'm also curious where you get PIC0 from? In the case of NFSIII, as seen in my pic, it perfectly pulls in a beautiful transparent game logo. Does that come from psxdatacenter too? I didn't see it there. Some games don't have the beautiful transparent logo

**Comment by sahlberg** [comment]
Done, except of the PIC1 rotation suggestion. the defaults from psxdatacentre images are all bad so click to rotate will just rotate between bad pictures. And we should not encourage the defaults.

What we need to have is curated links to good images. Best is if you send me a pull request with updates in gamedb.py to good art, or less good is if you just tell me which games you need art for and I will try to find and update gamedb with it.

The icons that are pulled are usually from gamedb.py
https://github.com/sahlberg/pop-fe/blob/master/gamedb.py

Only if nothing is found for the game in this db will pop-fe go to psxdatacentre and use it. This is the source of last resort.

**Comment by sahlberg** [comment]
I have added a better image for PIC1 for hot pursuit. Try regenerating it and it should look better.

**Comment by wad11656** [comment]
Thank you I'm eager to try with the new Windows exe

**Comment by sahlberg** [comment]
You can find the most recent build here:  https://github.com/sahlberg/pop-fe/actions/runs/6282602543
Under the ACTIONS tab there will be an automatic new build for every push.

**Comment by wad11656** [comment]
I'm dumb and don't know how to get the UI (`pop-fe-psp.ui`?) working with the newly downloaded `pop-fe-psp.exe` from the "Artifact" `.zip` file on that page, which didn't seem to come packaged with the UI part? sorry.

I know this isn't the right place to ask but I just wanted to quickly ask if you were keeping record of the ppf patches in your `ppf` folder -- As in, keeping record of the game name for each GAME ID ppf, and what bug(s) each ppf file fixes? Where do those ppf patches come from, anyway? Are you personally making any of them yourself?

**Comment by sahlberg** [comment]
I will try to test the pop-fe-psp.ui later once I get access to a windows machine to test with.

The PPFs,  we rarely need them for when creating EBOOTS or PKGs for PSP/PS3 as they both have special ways to feed things like 'libcrypt' to their emulators (semi-recently discovered that both of these can take both the 'magic-word' that solves libcrypt but also can take a special form of sbi files, which we can now regenerate. Both these go into the EBOOT or ISO.BIN.EDAT and solves that for both platforms. This solves most of the incompatibilities.

We also recently learned how to add "config" commands to the emulators, the ones on ps3 a few weeks back, and the ones on psp just a few days ago, so research is still going on by the folks that know those things. I don't, I just add the "config" data that they tell me to add to fix certain games.
Some games do need PPF patching and I also just add these when people report issues and the guys that know this stuff debug the issue and create a ppf and give it to me.

A good place to find this process is this thread:
https://www.psx-place.com/threads/ps1_netemu-external-configs-and-ad-hoc-params.41504/
Read through it. This is where a user on psx-place, mrjaredbeta, works with and annouces new configs to fix games that he and kozarov debugs and fixes.
For now, ypou can report games that have issues on the ps1_netemu emulator there and those guys may be able to find a fix, either a config setting or a ppf and then I will add it to pop-fe.

**Comment by sahlberg** [comment]
Try the latest artefacts, the pop-fe-psp.ui issue shoudl be fixed now.
