### ISSUE TITLE
Fix eboot.pbp for CDDA Enable

### ISSUE THREAD

**Issue by 64ghost** [sahlberg/pop-fe#44]
Add lines to sources or create a Python file

`fEBOOT=open('EBOOT.PBP','r+b')  ; opening a file`
`fEBOOT.seek(0x24)`
`data = fEBOOT.read(4)`
`PSAR=int.from_bytes(data,'little') ;  obtaining a PSAR address`
`fEBOOT.seek(PSAR+0x81b)`
`fEBOOT.write(b'\x80\x00\x00')  ; recording maximum CD disk size (80 min)`
`fEBOOT.close()`

**Comment by sahlberg** [comment]
Why do we need this?  The eboot contains ATRAC3 audio so we don't even need the CDDA tracks.

**Comment by 64ghost** [comment]
Some games even with ATRAC3 audio without this fix there was no sound.I don't remember the names of the games anymore.

**Comment by sahlberg** [comment]
ok, can you try to find a game that needs this so I can test with?

**Comment by Goatman13** [comment]
I think this could be already fixed with: https://github.com/sahlberg/pop-fe/commit/51e24ec48f22f24f91b86a66220a827b0f083cfe
Not tested, but it looks like similar issue with different outcome. Hard patching PMIN/PSEC/PFRAME on lead-out is a bad idea anyway.
