### ISSUE TITLE
NEKKETSU OYAKO NTSC-J  error

### ISSUE THREAD

**Issue by nydalap** [sahlberg/pop-fe#48]
Hello
When I try to create a PKG I get this error.
Best regards 
![nekketsu oyaku](https://github.com/sahlberg/pop-fe/assets/28576301/3d53795d-4c19-4f30-a4b0-790ff657b42f)

**Comment by sahlberg** [comment]
This game does ot have a system.cnf file so I have added an alternative way to fetch the disc ID.
The fix is in this build once it becomes available: https://github.com/sahlberg/pop-fe/actions/runs/6346842042

I have tested this game and verified that it works now.
