### ISSUE TITLE
[REQUEST] add my Bugs Bunny - Lost in Time config

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#51]
Hello, sorry to bother you, could you please add this config? 

https://www.mediafire.com/file/ek9uu0m4tokz9gy/BBLIT.zip/file
Fixes the hangs, audio and gets rid of the lag.

**Comment by sahlberg** [comment]
What about SLES-01726 ?
Do we need the config for that disc too?

**Comment by Webardo** [comment]
I believe it should also work, however, please don't upload that config yet. I will edit it a bit and add a SLES-01726.bin.

**Comment by Webardo** [comment]
Okay, just got all working. SLES-01726 also runs fine with this, and as such I provided a SLES-01726.bin file too.

Also included the Re-Volt config. From what I know, the PAL version doesn't have problems, so I only included the SLUS-00851.bin for it.

https://www.mediafire.com/file/orqq65jvdm892lz/pspconfigs.zip/file

**Comment by sahlberg** [comment]
Thanks. Configs added and a new build has started in
https://github.com/sahlberg/pop-fe/actions/runs/6442923146
