### ISSUE TITLE
Dragon Warrior can't be converted.

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#52]
Hello, it's me again. How you doing?

Sorry to bother. Going straight to the point, this game (both discs SLUS-01206 and SLUS-01346) shows the following issue:
cdrom: line in system.cnf does not contain a proper id, read disc label instead
ID DRAGONWAR
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 349, in on_path_changed
  File "pop-fe-psp.py", line 181, in update_assets
  File "pop-fe.py", line 180, in get_game_from_gamelist
KeyError: 'DRAGONWAR'

The issue comes from the game itself though. Disc 1 has this in the cnf file "SLUSP012.06;1" instead of "SLUS_012.06;1". Same thing applies to disc 2, with it having "SLUSP013.46;1" instead of the proper "SLUS_013.46;1".

Is it too much trouble to fix?

**Comment by sahlberg** [comment]
Not too much trouble at all.  Pop-fe needs to be perfect so eveything like this needs to be fixed.

I already have a database for "broken" disc-ids so I just had to add these two disks to it and now they are re-mapped 
correctly to the right id.

Thanks!

**Comment by Webardo** [comment]
I should be thanking you, the least I can do is notify of issues.

Will test in a few moments and comment how it goes :).

**Comment by Webardo** [comment]
Works great, thank you!
