### ISSUE TITLE
NTSC to PAL ported configuration breaks 50hz/pal.

### ISSUE THREAD

**Issue by ghost** [sahlberg/pop-fe#57]
Ex: Unjammer lammy on vita. 
Pop-fe correctly identifies the game as pal and applies the ported configuration from the NTSC pkg... if you then try to run the game the bottom of the screen is cut off.  Maybe timings are also wrong.
I remember having the same issues in the past, when I tried to give a PAL game a NTSC game id.
Is it possible to add a switch to skip the configuration step?

**Comment by sahlberg** [comment]
Can you report this over at https://gbatemp.net/threads/new-mode-to-fix-ps1-games-for-psp-and-psvita.607286/page-26
that is where the folks working on the conifgs hang out.
They can maybe reproduce and create a better config and then I can insert it in pop-fe.
