### ISSUE TITLE
Spyro 2 and 3 (PAL) crash on PS3

### ISSUE THREAD

**Issue by RollPlayStation** [sahlberg/pop-fe#58]
I tried to make a PKG with the PAL versions of some Spyro games, being my two favourites: Gateway to Glimmer and Year of the Dragon. But when I get to a new level on either, the screen stays black. They had their magic words injected, so any particular cause for why they don't work via pop-fe?

**Comment by sahlberg** [comment]
These games might need a configuration setting to tweak the emulator to avoid these hangs.
Adding configuration options to the emulator is fairly recent but we don't have any for the Spyro games yet.

Please jin this thread and ask about these games. https://www.psx-place.com/threads/ps1_netemu-external-configs-and-ad-hoc-params.41504
The people that work on reverse engineering the configs and creating new configs for games that have issues are all in that thread.
If they can find a config that works then I can add it to pop-fe so it is automatically applied in the future.

**Comment by sahlberg** [comment]
Check with psx-place, maybe htey can create a patch to prevent the crashes.
