### ISSUE TITLE
Two japanese Puzzle Games present an error when converting with Pop Fe 

### ISSUE THREAD

**Issue by Snowbro88** [sahlberg/pop-fe#63]
Hello, I want to report 2 other games that present an error when converting with pop-fe, they seem to be similar to the problem of not having a correct Game ID and when starting with the conversion of the audio tracks, they are the following

TwinBee: Taisen Puzzle-Dama
Uchuu Seibutsu Flopon-kun P!

They are 2 interesting Puzzle games exclusive to Japan that in theory with the conversion of audio tracks to AT3 should take up little space.

If it could be reviewed I would greatly appreciate it.

**Comment by sahlberg** [comment]
Ah, these games do not have a system.cnf file so I had to manually add them to an alternative database for detection.

They both detect correctly now.
Thanks for reporting these games. I added a pic0 logo for the games too but could not find a nice hi-res image to use for pic1. Let me know if you have good links to background images and I can add them to these games.

**Comment by Snowbro88** [comment]
I usually prepare my own backgrounds, almost all the material is extracted from gamesdb launchbox or I usually use the same cut-out box arts, in the case of Japanese games it is difficult to do a good customization, for Twinbee you could put any background from any of their popular titles.

Thank you for the quick response and I will try to continue reporting not very common games that have similar problems in being detected by Pop Fe.

**Comment by sahlberg** [comment]
Can you email me directly?   ronniesahlberg@gmail.com
