### ISSUE TITLE
Support for Valkyrie Profile Spanish Translation (fused discs)

### ISSUE THREAD

**Issue by Snowbro88** [sahlberg/pop-fe#64]
Hello, I would like to ask if it is possible to add support for the Spanish translation of Valkyrie Profile?, now that there is a configuration that solves the known problems.

The issue with this translation is that the author of the Spanish patch merged the 2 discs into a single .bin image and that it also does not have a .cue and apparently does not include its own Game ID, in this compilation in archive org you will find this pre-patched game.

[Spanish PS1 Translations](https://archive.org/details/psx-compilacion-de-traducciones-en-espanol_202305) 

I don't know how complicated it is and I know that it is not a common request but I hope it can be reviewed, when converting with PSX2PSP if it does, but it does not work correctly due to known problems.

Thank you.

**Comment by sahlberg** [comment]
I have added now that this translation of ValkyrieProfile will match with 'SLUS01179'
It is really simple to patch these games into pop-fe : see here how this game is made to be recognized:
https://github.com/sahlberg/pop-fe/commit/493cfe4637144988fd42379e851ec580a58804d9

The md5 sum is computed over the first 1Mb of data and should be unique across games.
When you run pop-fe or pop-fe-psp and it can not recognize the game it will print somehting like this in the command terminal : 
MD5 fingerprint 1808dd8b039de821d347167930b0bcf1

That fingerprint is what goes into gamedb.py and matches it up with a genuine release.

Now, I am not super interested in fan-modified games so I don't think I will work on adding any more.
But I am not against adding more, it is just I will not do the work to check the games and add them to the matching database.
If you want to add more games to be matched like this that is great. Create the patches, test them and then send me a pull request here on github and I will merge your additions.

the patches you create should be like this one:
https://github.com/sahlberg/pop-fe/commit/493cfe4637144988fd42379e851ec580a58804d9
then just send them to me as a pull request.

**Comment by Snowbro88** [comment]
Understood Boss.
