### ISSUE TITLE
The imagem looks a little downscale, compare to PSX2PSP 1.4 Process

### ISSUE THREAD

**Issue by felonyf0x** [sahlberg/pop-fe#69]
very nice tool, now the games multi-tracks works perfectly, but i have a impression, when i do the conversion with that other programs, the game looks a little better, i say the image quality looks a little downscale with pop-fe... this could be a wrong impression about the image when i look, but i will try to post to Pictures Screen to compare... i was thinking, if this could be because a Pal Version looks a litte better or a NTSC, i realy don't know... i will test more and back here to tell more about it.

**Comment by sahlberg** [comment]
I don't think this is a pop-fe issue, as we don't modify anything on the disc image itself and (except for CDDA tracks) the disk image stored inside the EBOOT is 100% identical to the original disc image.

The difference you might see might be due to the different resolution between PAL and NTSC.
