### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Desz5** [sahlberg/pop-fe#71]
I'm trying to convert all my playstation games but sometimes i get the following error, and the pkg is not created.

Creating D:/_PSX PKGs/PKG/011-Metal Gear Solid_pal.pkg
DISC SLES01370
TITLE METAL GEAR SOLID
GameID pop-fe-ps3-work/SLES01370
Create EBOOT.PBP at pop-fe-ps3-work/SLES01370/USRDIR/CONTENT/EBOOT.PBP
Injecting MAGIC WORD 0x0000 for disc 0
Injecting MAGIC WORD 0x0000 for disc 1
Create ISO.BIN.DAT pop-fe-ps3-work/SLES01370/USRDIR/ISO.BIN.DAT
Signing pop-fe-ps3-work/SLES01370/USRDIR/ISO.BIN.DAT
Create ISO.BIN.EDAT
Create PKG
Traceback (most recent call last):
File "pkg.py", line 595, in <module>
File "pkg.py", line 590, in main
File "pkg.py", line 484, in pack
MemoryError
[6516] Failed to execute script 'pkg' due to unhandled exception!
Finished. D:/_PSX PKGs/PKG/011-Metal Gear Solid_pal.pkg created

There is enough memory free on the system.
Can anyone tell me what causes this?

**Comment by sahlberg** [comment]
That is an error when python tries to allocate memory but it fails.
