### ISSUE TITLE
Crash Bandicoot 3 (SCES-01420) not working in PSP

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#73]
I've been testing the tool, and all the games I've tried so far have worked. I conducted the tests on a PS Vita with Adrenaline. However, with Crash Bandicoot 3 PAL version (SCES-01420), the game starts, but upon reaching the Universal Interactive Studios logo, it freezes, and a few seconds later, Adrenaline crashes. It seems that the issue is caused by the configuration in Pspconfigs because the bin-cue files used match the redump database.

**Comment by sahlberg** [comment]
Please report this over at https://gbatemp.net/threads/new-mode-to-fix-ps1-games-for-psp-and-psvita.607286/page-50
That is where the people that create the configs hang out.

**Comment by AdrCant** [comment]
I downloaded pop-fe again and converted the game once more, and now it worked correctly. It seems something was downloaded incorrectly or got corrupted, and that's why it wasn't working. Sorry for bothering you.
