### ISSUE TITLE
Fix for Driver - You're the Wheelman (SLES-01978) in PSP

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#74]
A game that has issues on PSP but has a solution is Driver - You're the Wheelman in its Spanish version (SLES-01978). This version works fine until after completing the tutorial; the game freezes when you try to restart any mission after that point. To fix it, the Game ID in Psx2Psp was changed from the PAL Spain version to the PAL UK (SLES-01816), and the game works without issues. I would like to request that this fix be added to Pspconfigs if possible.

**Comment by sahlberg** [comment]
Please report this over at https://gbatemp.net/threads/new-mode-to-fix-ps1-games-for-psp-and-psvita.607286/page-50
That is where the people that create the configs hang out.

**Comment by sahlberg** [comment]
Configs have been added by mrjaredbeta for this game.
It will be available when the build finishes at
https://github.com/sahlberg/pop-fe/actions/runs/7482627118
