### ISSUE TITLE
Support for Thrill Kill (SLUS-00752)

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#75]
I would like to inquire whether it would be possible to add support for the game Thrill Kill. This game is not listed on psxdatacenter, seemingly because it was never officially released. This game would undoubtedly benefit from the conversion of cdda to at3, given its multitrack nature.

**Comment by sahlberg** [comment]
Added.

This will be available in pop-fe once this build finishes:
https://github.com/sahlberg/pop-fe/actions/runs/7470341529
