### ISSUE TITLE
Support for Resident Evil 1.5

### ISSUE THREAD

**Issue by AdrCant** [sahlberg/pop-fe#76]
Hello again. A game/mod I've come across is the Magic Zombie Door for Resident Evil 1.5, the beta of Resident Evil 2 that leaked on the internet around 2013. This mod makes this beta playable, fixing several errors it had. If possible, I would like to request support for this mod. Unfortunately, the game doesn't have an ID, but you could add this ID: SLUS-00000.
Here's a link where you can download the game: https://cdromance.com/psx-iso/resident-evil-1-5-magic-zombie-door-hack/

**Comment by sahlberg** [comment]
Very nice find.

Added to the database and it will be available when https://github.com/sahlberg/pop-fe/actions/runs/7646586896 finished building.

Do you have any suggestions on what to use for PIC0 (logo) PIC1 (background) ?

**Comment by AdrCant** [comment]
I could suggest you try these images from the games database on LaunchBox.
Link: https://gamesdb.launchbox-app.com/games/images/81966-resident-evil-15
