### ISSUE TITLE
European title called Speed machines not recognized by Pop Fe.

### ISSUE THREAD

**Issue by Snowbro88** [sahlberg/pop-fe#80]
The following game Speed Machines (SLES-03930) flags this error when trying to convert with Pop Fe, perhaps requiring another form of identification.

![Speed Machines Error](https://github.com/sahlberg/pop-fe/assets/38197627/a51937c3-d83a-4d58-93e5-a20e503affa2)

**Comment by sahlberg** [comment]
That one is identified correctly in my work-branch that I have used for a while to collect all the compatibility configs for the emulators on psp and ps3.

There are massive compatibility updates that were only available in github scratch builds but things have slowed down now.

I have made a new release with the latest complete changes from the work-in-progress I used for the psp/ps3 update work.
Can you try downloading the latest release and try again?

**Comment by sahlberg** [comment]
The background image is not good but I could not find anything better.
I think what it would need is a nice pic1 background image  but I can not find one.
IF the game is important enough to you and you add a pic1 fanart or background image to launchbox-app.com
then I can link to it and use it.
