### ISSUE TITLE
Output Directory only works for first conversion (PSP)

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#82]
Output Directory only works for first conversion (PSP)

On the PSP GUI, setting the 'Output Directory' only works for the first conversion, and has to be reset for each new disc.

Example:
1. Select new disc
2. Set 'Output Directory'
3. Select 'Create EBOOT.PBP'
Result: EBOOT is saved to a folder inside the specified output directory.

4. Select new disc
5. Select 'Create EBOOT.PBP'
Result: EBOOT is saved to a folder inside the pop-fe application folder instead of the specified output directory.

**Comment by sahlberg** [comment]
Fixed in https://github.com/sahlberg/pop-fe/actions/runs/7765164178
