### ISSUE TITLE
Request: Add option for output EBOOT folder to be named after game title, not game ID (PSP)

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#83]
Currently the output PSP EBOOT.PBP is output to a folder named after the game ID (eg. SCUS94231). For user convenience, it would be useful as an option for the output folder to be named after the game title instead (eg. 3XTREME).

There is a limit of 31 characters for the folder name, otherwise the EBOOT will show as corrupted in the XMB.

**Comment by sahlberg** [comment]
I don't know if it makes sense to add as a checkbox to the end user as this is a VERY niche feature. I imagine most users never look at the directory structure.
What about I change the directory name from the current 9 character disc id ('SLUS12345') to instead be the disc id + a space + the first 20 characters of the game name and make this the default way the name is done.
I.e. 'SLUS12345 Some Game Name, maybe truncated'

**Comment by bombjack84** [comment]
If most people don't look at the directory structure, does it matter then what the folder name is? Might as well cater for those that do in that case. Your suggestion is a good compromise though, although putting the game name first might be better for sorting purposes.

**Comment by bombjack84** [comment]
On second thoughts, maybe it's best not to change this and annoy anyone partway through converting. I'm ok to manually change the output folder names.
