### ISSUE TITLE
Request: Add options for scaling and framing ICON0 (PSP)

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#84]
The default ICON0 artwork is quite small and blurry on the PSP screen. An option to do a sharp rather than smooth downscale of the artwork would be nice.

Also an option to remove the grey/black frame and surrounding whitespace around the artwork would be welcome, so that the artwork maximises the 80x80 limit.

Example - Default (1st pic), Requested (2nd pic):

![default ICON0](https://github.com/sahlberg/pop-fe/assets/158531648/e83054fb-9fb0-4c34-b3c9-41f2cf361871)

![suggested ICON0](https://github.com/sahlberg/pop-fe/assets/158531648/2b98963a-2ba9-4b8c-89ce-27b523e1006b)

(size doubled for clarity)

**Comment by sahlberg** [comment]
Try this build : https://github.com/sahlberg/pop-fe/actions/runs/7764972012
this is probably as good as it's gonna get.

I reworked the frame (to make it a couple of pixels larger in x/y
I also reworked it to reduce the number of rescales are done to icon0 so we not should only re-size once and not multiple times.
Finally I changed the interpolation from Bilinear to Hamming which should produce a sharper result in the one re-size operation I now do.

**Comment by bombjack84** [comment]
This build gives the following error:

ID SLPS00965
Creating EBOOT
DISC SLPS00965
TITLE ...IRU!
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 589, in on_create_eboot
  File "pop-fe.py", line 2779, in create_psp
UnboundLocalError: local variable 'image' referenced before assignment

**Comment by sahlberg** [comment]
Ah,
try this:
https://github.com/sahlberg/pop-fe/actions/runs/7765535046

**Comment by bombjack84** [comment]
Thanks, that is a bit sharper/clearer.
