### ISSUE TITLE
CHD files crashes Pop-fe ps3

### ISSUE THREAD

**Issue by fredward85** [sahlberg/pop-fe#86]
Hi, I used Pop-fe and works great but chd files when importing to pop-fe ps3 crashes the software.  No error messages occur only closes the software. Bin/cue files work fine. I tried running as admin with same issue as well. Thought I'd reach out if there was a fix for that?

**Comment by sahlberg** [comment]
CHD support is pretty ad-hoc. It requires that you have chdman installed and that it can be found in the PATH.

Make sure that have chdman installed and make sure it is in PATH. The best way to check it is in PATH is to just open a termianl/command window and verify that it finds the executable when you try to just run it as "chdman"
