### ISSUE TITLE
(PSP) IndexError: bytearray index out of range (Aces of the Air, Buster Bros Collection + others)

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#87]
This error happens when converting Aces of the Air and several others to PSP:

[INFO]  Output directory: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work
[INFO]  Opening cue: C:\Users\This\Downloads\PS1\Aces of the Air (USA)\Aces of the Air (USA).cue
[INFO]  Merging 14 tracks...
[INFO]  Wrote C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.bin
[INFO]  Wrote new cue: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.cue
ID SLUS01470
Found an external config for SLUS01470
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/e137a442f38d45c77c7b6f74848d0849
Creating EBOOT
DISC SLUS01470
TITLE ACES OF THE AIR
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_03.wav to pop-fe-psp-work/TRACK_0_03.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_04.wav to pop-fe-psp-work/TRACK_0_04.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_05.wav to pop-fe-psp-work/TRACK_0_05.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_06.wav to pop-fe-psp-work/TRACK_0_06.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_07.wav to pop-fe-psp-work/TRACK_0_07.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_08.wav to pop-fe-psp-work/TRACK_0_08.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_09.wav to pop-fe-psp-work/TRACK_0_09.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_10.wav to pop-fe-psp-work/TRACK_0_10.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_11.wav to pop-fe-psp-work/TRACK_0_11.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_12.wav to pop-fe-psp-work/TRACK_0_12.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_13.wav to pop-fe-psp-work/TRACK_0_13.aea
End of input file.

Converting pop-fe-psp-work/TRACK_0_14.wav to pop-fe-psp-work/TRACK_0_14.aea
End of input file.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 586, in on_create_eboot
IndexError: bytearray index out of range

**Comment by sahlberg** [comment]
Try the latest build of pop-fe.
I just tried to convert that game and it converted fine.
