### ISSUE TITLE
[PSP] FFVIII PAL (Europe/Australia) Discs 2-4 not recognized in pop-fe-psp, and don't boot

### ISSUE THREAD

**Issue by wad11656** [sahlberg/pop-fe#88]
Edit: Based on the logs (and my testing with libcrypt-patched ISO's), it's just a libcrypt issue: I guess since Disc 1 is recognized, it gets the correct subchannel blob injected...but since Discs2-4 aren't recognized, pop-fe neglects them

SLES-12080, -22080, 32080

edit2: with the libcrypt patch applied from here 

https://ia802507.us.archive.org/view_archive.php?archive=/30/items/lib-crypt-ppf-patches/LibCrypt%20PPF%20Patches.rar

...disc 2 reportedly (according to a guy I was helping getting this to run) suffers freezes like the ones described for ffVIII in the compatibility list below (ie when drawing magic), so maybe our gbatemp friends can make a compatibility fix for it, if fixing the sub channel injection doesn't fix it

https://cdromance.com/utils/popsloader/Pops-Compatibility-List.htm

**Comment by sahlberg** [comment]
There were some database errors. I have fixed them up and they detect correctly now by pop-fe.
This build will contain it when it finishes building:
https://github.com/sahlberg/pop-fe/actions/runs/8036430000
