### ISSUE TITLE
Add exception for Tetris - The Grand Master's ZN-2 to PSX conversion.

### ISSUE THREAD

**Issue by Webardo** [sahlberg/pop-fe#89]
Could you please add this one to your database? It's more of a homebrew port than a hack, and it also is a pain in the ass to patch, so I'll upload it here for you: https://www.mediafire.com/file/i5u8as0n6x6j7tc/Tetris_-_The_Grand_Master_%2528USA%2529.zip/file.

This is the USA patch, so I believe a valid code to give it would be something like "TGMU-26142".

I give you my thanks beforehand, and if you can't nor want to do this, it is totally understandable.

**Comment by sahlberg** [comment]
Added.
Will be in this build once it finishes:
https://github.com/sahlberg/pop-fe/actions/runs/7980420413

I already had this game in the database but it had a different md5 checksum so that was why the detection failed.
I have added the checksum for this disk so it should detect now.
