### ISSUE TITLE
game_id Argument does not skip ISO creation

### ISSUE THREAD

**Issue by HiroTex** [sahlberg/pop-fe#9]
I was using the argument --game_id to set the Game's ID and skip the ISO conversion, but it seems it does not skip it because it's needed for the libcrypt instructions later on? I noticed it because the game Pink Panther - Pinkadelic Pursuit [SLUS01451] had an issue when trying to get the game's ID using the function get_disc_ids (probably a Bad ISO conversion? Bad Rip? I'm not too sure), so I moved the lines:
print('Convert CUE to a normal style ISO') if verbose else None
disc_ids = get_disc_ids(cue_files)
print('disc_ids', disc_ids)

inside the case "if not game_id", before game_id = disc_ids[0], and used the param --game_id as usual, then the game was converted successfully and works as intended with full BGM (it's a multi bin game).

I know this is not a good approach, it will probably prevent the libcrypt section from properly doing its work if game_id is used, but as a suggestion it would be better to skip the ISO conversion part if a game_id is already set by the user if possible, to save time and to possibly avoid this problems.

**Comment by sahlberg** [comment]
> I noticed it because the game Pink Panther - Pinkadelic Pursuit [SLUS01451] had an issue when trying to get the game's ID using the function get_disc_ids (probably a Bad ISO conversion? Bad Rip?

It is probably just that the system.cnf file is sligtly different format and I can not parse it fully yet.
Can you mount the ISO and paste the content of system.cnf ?
It should be a small small text file.

**Comment by HiroTex** [comment]
Well, here it is, I don't see any noticeable difference when comparing it to other CNF files, besides the "SLuS" string, which I tried to change and didn't work.

[SYSTEM.zip](https://github.com/sahlberg/pop-fe/files/8366931/SYSTEM.zip)

I also noticed that the resultant ISO File weights way less than the original bin, is this to save time or is it a bug indeed?
![image](https://user-images.githubusercontent.com/85416604/160503710-5e88c411-0f49-4d94-9a80-a911e45df048.png)

**Comment by sahlberg** [comment]
The issue looks like pycdlib can not even parse the iso filesystem properly and that is why it fails.
The current changes I made to the master branch should avoid this and skip trying to parse the iso
if you either specify the game-id via --game_id or via the file GAME_ID

**Comment by HiroTex** [comment]
It's working perfectly now! Thanks, you are doing a really great work here.

**Comment by sahlberg** [comment]
Try current master.  I added a fix for the SLuS  but also refactored some
code that IF you provide a --game_id argument or IF GAME_ID exists then it
will skip creating the iso or look for system.cnf
