### ISSUE TITLE
(PSP) 'Force NTSC' option causes exception with some games

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#90]
Related to closed issue 87, where I couldn't get Aces of the Air and Buster Bros Collection to convert, it's the 'Force NTSC' option causing the below exception with those games and probably more. I know I could disable the option for those games, but thought it was worth mentioning.

[INFO]  Output directory: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work
[INFO]  Opening cue: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\Buster Bros. Collection (USA).cue
[INFO]  Merging 61 tracks...
[INFO]  Wrote C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.bin
[INFO]  Wrote new cue: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.cue
ID SLUS00208
Found an external config for SLUS00208
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/a7761ef47cc3773d2904ea08548b691b
Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/35b28e246c8c2ce7afa9b6d801257942
Creating EBOOT
DISC SLUS00208
TITLE BUSTER BROS. COLLECTION
Converting pop-fe-psp-work/TRACK_0_02.wav to pop-fe-psp-work/TRACK_0_02.aea
End of input file.
*** etc. ***
Converting pop-fe-psp-work/TRACK_0_61.wav to pop-fe-psp-work/TRACK_0_61.aea
End of input file.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 592, in on_create_eboot
IndexError: bytearray index out of range

**Comment by sahlberg** [comment]
Aha, I see. There was a bug in when injecting the command into the config that it did not check the siize of the config.
(configs that only contain PSP data but not VITA data are smaller than configs that contain both.)

Checks are added and this will work in this build once it finishes:
https://github.com/sahlberg/pop-fe/actions/runs/8015056782

**Comment by bombjack84** [comment]
The fix works well with the affected games, thanks.
