### ISSUE TITLE
(PSP) Colony Wars - Vengeance (USA) config error

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#92]
This game is ID SLUS00722 and has an associated config, but pop-fe looks for a config called SLES-00722.bin instead of the existing SLUS-00722.bin.

[INFO]  Output directory: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work
[INFO]  Opening cue: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\Colony Wars - Vengeance (USA).cue
[INFO]  Merging 2 tracks...
[INFO]  Wrote C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.bin
[INFO]  Wrote new cue: C:\Users\This\Downloads\pop-fe-ui\pop-fe-psp-work\MBd1.cue
ID SLUS00722
Found an external config for SLUS00722
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-psp.py", line 366, in on_path_changed
FileNotFoundError: [Errno 2] No such file or directory: 'pspconfigs/Colony Wars - Vengeance/SLES-00722.bin'

**Comment by Webardo** [comment]
Just rename the SLUS-00722.bin config to SLES-00722. I'll do a pull request in a few moments to fix that however.

**Comment by Webardo** [comment]
Fixed in this build: https://github.com/sahlberg/pop-fe/actions/runs/8034810943
