### ISSUE TITLE
cu2 file missing 

### ISSUE THREAD

**Issue by nono2poor** [sahlberg/pop-fe#95]
can't say more seamns to be an issue in  Cue2cu2
`Fetching SND0
Found cached prebuilt PIC0 https://github.com/sahlberg/pop-fe-assets/raw/master/pic0/433bf73cbf533a3f585763a93074f17e
Found cached prebuilt PIC1 https://github.com/sahlberg/pop-fe-assets/raw/master/pic1/2968f71ecbd9303d7a945c14268a74c2
Need to create a temporary cue/bin pop-fe-ps3-work/TMPCUEd2.cue pop-fe-ps3-work/TMPIMGd2.bin
Creating game.pkg
DISC SCES01237
TITLE TEKKEN 3
Found cached prebuilt SND0 https://github.com/sahlberg/pop-fe-assets/raw/master/snd0/00f9d34a0fa7f8196c81f84b9471d363
Cue2cu2: Error while processing C:/Users/nono/Downloads/Tekken 3 (Platinum) (EU)/Tekken 3 (Platinum) (EU).cue: Could not find binary file.
Converting pop-fe-ps3-work/TRACK_0_02.wav to pop-fe-ps3-work/TRACK_0_02.aea
End of input file.

Converting pop-fe-ps3-work/TRACK_0_03.wav to pop-fe-ps3-work/TRACK_0_03.aea
End of input file.

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "pop-fe-ps3.py", line 792, in on_create_pkg
  File "pop-fe.py", line 1143, in create_ps3
  File "pop-fe.py", line 847, in get_toc_from_cu2
FileNotFoundError: [Errno 2] No such file or directory: 'pop-fe-ps3-work/TMP0.cu2'
`

**Comment by sahlberg** [comment]
Cue2cu2: Error while processing C:/Users/nono/Downloads/Tekken 3 (Platinum) (EU)/Tekken 3 (Platinum) (EU).cue: Could not find binary file.

There is something wrong with your .cue file. It could not find the bin file that is referenced.
Probably try to open the cue file with an editor and see what file it refers to for the bin file.
Maybe there is a typo or something that you need to fix.
