### ISSUE TITLE
Unknown ID: Abe a GoGo (Japan) (Demo) - 80eede37cdb739de28eb404da9885b7e

### ISSUE THREAD

**Issue by bombjack84** [sahlberg/pop-fe#99]
Unknown ID: Abe a GoGo (Japan) (Demo) - 80eede37cdb739de28eb404da9885b7e

**Comment by sahlberg** [comment]
Great. I will start adding these tomorrow.

A question for you. The discs that are DEMOs, how should I handle them?
Should I just re-map them to the full game,
or should I create a new entry for them?

I was thinking maybe for if there is a demo for SLUS12345
then I create a new entry for 'DEMO12345' and map the md to this new entry.
I can use the same existing links to icon/pic/snd
but append a '(DEMO)' to the end of the title to indicate it is not the
full game.

**Comment by bombjack84** [comment]
How did you handle adding the demos in this issue? https://github.com/sahlberg/pop-fe/issues/72

I notice those discs have the alpha part of their IDs all end in D - SCED/SLED etc.
Maybe you could keep the first three characters (SLU/SLP/SCE etc.) but make the fourth a D.
As long as the EBOOTs work and the original game's artwork is detected, that is.

**Comment by sahlberg** [comment]
I added them manually, or rather, I had a script that converted all 500 or so of them into proper entries for the db.
These were all kind of disc magazine cover disks so they all had a bunch of small demos on them.
Don't know what to do for he assets in that case. Maybe someone will add pic1 as picture of the magazine front page or something.

**Comment by sahlberg** [comment]
added in
https://github.com/sahlberg/pop-fe/actions/runs/8261235237
